plugins {
    id 'fabric-loom' version "${loom_version}"
    id 'maven-publish'
    id 'me.modmuss50.mod-publish-plugin' version "0.5.1"
}

def mcVersion = stonecutter.current.version

version = "${project.mod_version}-$mcVersion"
group = project.maven_group

repositories {
    mavenCentral()
    maven {
        url = "https://api.modrinth.com/maven"
    }
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${stonecutter.current.project}"
    mappings "net.fabricmc:yarn:${property('yarn_mappings')}:v2"
    modImplementation "net.fabricmc:fabric-loader:${property('fabric_loader')}"

    // Fabric API. This is technically optional, but you probably want it anyway.
    modImplementation "net.fabricmc.fabric-api:fabric-api:${property('fabric_api')}"

    modImplementation include ("maven.modrinth:midnightlib:${project.midnightlib_version}")
}

base {
    archivesName = "linkart-refabricated"
}

processResources {
    inputs.property "minecraft", mcVersion
    inputs.property "version", mod_version
    inputs.property "loader_version", fabric_loader

    def map = [
            "minecraft": mcVersion,
            "version": mod_version,
            "loader_version": fabric_loader
    ]

    filesMatching("fabric.mod.json") {
        expand map
    }
}

loom {
    runConfigs.all {
        ideConfigGenerated true // Run configurations are not created for subprojects by default
        runDir "../../run" // Use a shared run folder and create separate worlds
    }

    fabricModJsonPath = rootProject.file("src/main/resources/fabric.mod.json")
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}" }
    }
}

tasks.register('buildAndCollect', Copy) {
    group = 'build'

    from(tasks.named('remapJar').flatMap { it.archiveFile })
    from(tasks.named('remapSourcesJar').flatMap { it.archiveFile })
    into rootProject.layout.buildDirectory.dir("libs/${project.mod_version}").get().asFile

    dependsOn 'build'
}