# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.configuration-cache=true

# Mod properties
mod.version=6.1.1
mod.group=com.github.vini2003.linkart
mod.id=linkart
mod.name=Linkart Refabricated

# Global dependencies
deps.fabric_loader=0.18.3